spring:
  application:
    name: AdventureWorks_api
  datasource:
    url: jdbc:postgresql://dpg-d3sq5c7gi27c73drhs9g-a.oregon-postgres.render.com:5432/facturacion_vb0s
    username: facturacion_vb0s_user
    password: bHSftBj6m8pT7Eca7C26dRLnUNpzekXm
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

app:
  # Importante: el JWT secret debe ser Base64 válido y suficientemente largo (32 bytes mínimo para HS256)
  jwt-secret: 2466228b5696524a55abeb0d24574430878f7d5c6cbea8e4d5cabeebc5314685
  jwt-expiration-time: 3600000
